### ISSUE TITLE
Feature Request. Small icon on big icon.

### ISSUE THREAD

**Issue by lapster81** [SAP/macOS-icon-generator#15] opened 2024-06-25 12:49 UTC
Would be a super nice feature to be able to create an icon with a smaller icon on top of it, similar to what is shown in Dan Snelsons Setup Your Mac progress bars. Best shown with an image I suppose. Like the finder icon shown here with the church layered on top. Could be great for custom icons and branding. In fact think icons is already doing this with the uninstall icon, tho be able to change it to another icon and scale both of them accordingly would be really neat!

![Screen-Shot-2022-07-23-at-4-1 36 35-PM](https://github.com/SAP/macOS-icon-generator/assets/117836093/86fd5250-a4ad-4e1b-8eb5-b7143775a091)

Thanks for everything! /L

**Comment by mthielemann** [comment] 2024-07-23 17:36
This is more or less a duplicate of [this](https://github.com/SAP/macOS-icon-generator/issues/12) issue and is scheduled for Icons 2.1.0.

**Closed by mthielemann** 2024-07-23 17:36 UTC
Labels: duplicate
